---
title: "Guía 10"
author: "Danilo Perez"
date: "3/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pregunta 1

```{r}
rm(list = ls())
#install.packages("ggplot2")
library(ggplot2)
ggplot(data.frame(x=c(-6,6)), aes(x)) + 
  stat_function(fun=dnorm, args=list(mean=0, sd=1),
                geom="line", colour="red", size=1.2) +
  stat_function(fun=dnorm, args=list(mean=0, sd=1.5),
                geom="line", colour="black", size=1.2) +
  stat_function(fun=dnorm, args=list(mean=0, sd=2),
                geom="line", colour="blue", size=1.2) +
  ylab("Densidad") + theme_bw()
```

```{r}
# Normal estándar
x=seq(-6,6,0.01)
y=dnorm(x)
dn = data.frame(x,y)
ggplot(dn, aes(x,y)) + geom_line()
```


# Pregunta 2

```{r}
rm(list = ls())
library(ggplot2)
x = seq(0, 10, 0.01)
y = dunif(x, 0, 10)
df = data.frame(x,y)
rm(x,y)

ggplot(data = df, mapping = aes(x = x, y = y)) +
  geom_line() +
  geom_area(mapping = aes(x = ifelse(x>=6 & x<=10, x, 0)), fill = "maroon") +
  labs(x = "Disposición a pagar", y = "Densidad") +
  scale_x_continuous(expand = c(0,0), breaks = c(0,6,10), labels = c(0,6,10),
                     limits = c(0,12)) +
  scale_y_continuous(expand = c(0,0), breaks = c(0.10), labels = c(0.10),
                     limits = c(0,0.15)) +
  theme(panel.background = element_blank(),
        axis.line = element_line())
```


# Pregunta 3

```{r}
rm(list = ls())
library(ggplot2)
ggplot(data.frame(x=c(-4,4)), aes(x)) +
  stat_function(fun=pnorm, args = list(mean=0, sd=1),
                geom="line", colour="red", size=1.2) +
  stat_function(fun=pt, args = list(5),
                geom="line", colour="black", size=1.2) +
  stat_function(fun=plogis, args = list(),
                geom="line", colour="blue", size=1.2) +
  ylab("Distribución acumulada") + theme_bw()
```


# Pregunta 4

## a)
```{r}
rm(list = ls())
library(ggplot2)
quad = function(x) (x^3+2*x)
ggplot(data.frame(x=c(-2,2)), aes(x)) +
stat_function(fun=quad, geom = "line", size=1.2) + theme_bw()
```

```{r}
rm(list = ls())
library(ggplot2)
ggplot(data.frame(x=c(-2,2)), aes(x)) +
stat_function(fun=function(x)x^3+2*x, geom = "line", size=1.2) + theme_bw()
```

```{r}
rm(list = ls())
library(ggplot2)
#install.packages("dplyr")
library(dplyr)
x=seq(-2,2,length=1000)
y=x^3+2*x
data=data.frame(x,y)
data %>% ggplot(aes(x,y)) + geom_line(size=1.2) + theme_bw()
```

## b)
```{r}
library(ggplot2)
ggplot(data.frame(x=c(-10,10)), aes(x)) +
  stat_function(fun=function(x){(x^2+x)*cos(x)}, geom = "line", size=1.2) + theme_bw()
```

## c)
```{r}
library(ggplot2)
library(dplyr)
x=seq(-6,4,length=1000)
y=x^2+2*x-1
data=data.frame(x,y)
data %>% ggplot(aes(x,y)) + geom_line(size=1.2) +
  geom_text(aes(2,20, label=(paste(expression("y = x"^2*" + 2x - 1")))), parse = TRUE) + theme_bw()
```


# Pregunta 5

```{r}
library(ggplot2)
library(dplyr)
A=5
eps=1

x=seq(1,10,length=1000)
y=(A/x)^(1/eps)

data=data.frame(x,y)
data %>% ggplot(aes(x,y)) + geom_line(size=1.2) + xlab("Cantidad demandada") + ylab("Precio") +
  theme(panel.background = element_blank(),
        axis.line = element_line())

#Función de Demanda con elasticidad precio constante. Epsilon le da la elasticidad precio. Se grafica demanda inversa.
```


# Pregunta 6

```{r}
demanda = function(q) {30 - 2*q}
oferta = function(q) {2*q + 2}

#Rango de cantidades
x = 0:15

#Equilibrium quantity
q = uniroot(function(x) demanda(x) - oferta(x), range(x))$root
#Acá digo que Qd-Qs=0. Que busque entre el valor mínimo y máximo definido con range.

#Equilibrium price
p = oferta(q)

paste0("El precio de equilibrio es ", p, " y la cantidad de equilibrio es ", q)

ggplot(data.frame(x=c(0,15))) +
  stat_function(aes(x), fun = demanda, size=1) +
  stat_function(aes(x), fun = oferta, size=1) +
  labs(x = "Cantidad", y = "Precio") +
  scale_x_continuous(expand = c(0,0), breaks = c(5,10,15),
                     labels = c(5,10,15),
                     limits = c(0,18)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,32)) +
  annotate("point", x = q, y = p, colour = "grey10", size = 3) +
  annotate("segment", x = q, xend = q, y = 0, yend = p,
           linetype = "dashed", colour = "red") +
  annotate("segment", x = 0, xend = q, y = p, yend = p,
           linetype = "dashed", colour = "red") +
  annotate("text", x = 14.9, y = 3, label = "Demanda") +
  annotate("text", x = 12.5, y = 30, label = "Oferta") +
  theme(panel.background = element_blank(),
        axis.line = element_line())
```


# Pregunta 7

```{r}
library(ggplot2)
library(dplyr)
Q=seq(1,9,length=1000)
CT=3*Q^3-15*Q^2+50*Q+100      #Costo total#
CMg=9*Q^2-30*Q+50         #Costo marginal#
CMe=3*Q^2-15*Q+50+(100/Q)   #Costo medio#
CVMe=3*Q^2-15*Q+50          #Costo variable medio#

data=data.frame(Q,CT,CMg, CMe, CVMe)

data %>% ggplot() + 
  geom_line(aes(x=Q, y=CMg), linetype = "dashed", size=1.3) +
  geom_line(aes(x=Q, y=CMe), linetype = "solid", size=1.3) +
  geom_line(aes(x=Q, y=CVMe), linetype = "dotted", size=1.3)+
  labs(x = "Producción", y = "Costo ($)") + 
  ylim(0,150) + 
  geom_text(x=5.6, y=140, label = "CMg") +
  geom_text(x=1.1, y=142, label = "CMe") +
  geom_text(x=8.7, y=142, label = "CVMe") +
  theme(panel.background = element_blank(),
        axis.line = element_line())
```


# Pregunta 8

```{r}
library(ggplot2)
library(dplyr)

#Repetir NA 1000 veces
y = rep(NA,1000)
e = rep(NA,1000)
e[1] = rnorm(1)
y[1] = 0

for(t in 2:1000) {
  e[t] = rnorm(1)
  y[t] = y[t-1]+e[t]
  #y[t] = 0.5+y[t-1]+e[t] Le agregamos un drift
}

time = 1:1000
data = data.frame(time, y)
data %>% ggplot(aes(time, y)) + geom_line(size=0.8) +
  theme_minimal()
```


# Pregunta 9

## a)
```{r}
plot(arima.sim(list(order = c(0,0,1), ma=0.9), n=500))
#Defino parte AR=0, MA=0.9
```

## b)
```{r}
plot(arima.sim(list(order = c(2,0,0), ar=c(1.3, -0.7)), n=500))
```

## c)
```{r}
plot(arima.sim(model = list(order = c(2,0,1), ar=c(1, -0.9), ma=-0.8), n=500))
```








